import type { Metadata } from "next";
import { Imperial_Script } from "next/font/google";
import "./globals.css";

const imperialScript = Imperial_Script({
  variable: "--font-imperial-script",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${imperialScript.variable} ${imperialScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
